# Generated by Django 4.2.7 on 2023-11-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя пользователя')),
                ('phone', models.CharField(blank=True, default='', max_length=255, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('floor', models.CharField(blank=True, default='', max_length=255, verbose_name='Этаж')),
                ('flat', models.CharField(blank=True, default='', max_length=255, verbose_name='Домофон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderProductsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
    ]
