# Generated by Django 4.2.7 on 2023-11-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_orderproductscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Доставка'),
        ),
    ]
