# Generated by Django 4.2.7 on 2023-12-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductscount',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproductscount',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProductsCount',
        ),
    ]
