# Generated by Django 4.2.7 on 2023-12-02 16:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('vk_link', models.URLField(blank=True, default='', max_length=255, verbose_name='Ссылка на VK')),
                ('tg_link', models.URLField(blank=True, default='', max_length=255, verbose_name='Ссылка на Telegram')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
