# Generated by Django 4.2.7 on 2023-12-15 16:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79999999999', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tg_link',
            field=models.URLField(blank=True, default='https://web.telegram.org/', max_length=255, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vk_link',
            field=models.URLField(blank=True, default='https://vk.com/', max_length=255, verbose_name='Ссылка на VK'),
        ),
    ]
