# Generated by Django 4.2.7 on 2023-12-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_image_alter_product_calories_and_more'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproductscount',
            options={'verbose_name': 'Количество товара', 'verbose_name_plural': 'Количество товаров'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа'),
        ),
        migrations.AlterField(
            model_name='orderproductscount',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderproductscount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderproductscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Товар'),
        ),
    ]
