# Generated by Django 4.2.7 on 2023-12-15 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_options_alter_product_options_and_more'),
        ('cart', '0002_alter_orderproductscount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductscount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderproductscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар'),
        ),
    ]
